ALTER TABLE "APPVISAMANAGER"."PRINTOUT_TM30"
 ADD CONSTRAINT "FK_PRINTOUT"
 FOREIGN KEY ("MONASTIC_PROFILE")
 REFERENCES "APPVISAMANAGER"."MONASTIC_PROFILE" ("ID_PROFILE")
 ON UPDATE NO ACTION ON DELETE NO ACTION;

ALTER TABLE "APPVISAMANAGER"."MONASTIC_PROFILE" ADD "PRINTOUT_TM30" int;

ALTER TABLE "APPVISAMANAGER"."MONASTIC_PROFILE"
 ADD CONSTRAINT "FK_PROFILE_PRINTOUT"
 FOREIGN KEY ("PRINTOUT_TM30")
 REFERENCES "APPVISAMANAGER"."PRINTOUT_TM30" ("ID_PRINTOUT")
 ON UPDATE NO ACTION ON DELETE NO ACTION;

