REATE TABLE "APPVISAMANAGER"."APP_USER"
(
   IDUSER int not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
   EMAIL varchar(255),
   LOGIN varchar(255) NOT NULL,
   PASSWORD varchar(255),
   PHONENUMBER varchar(255),
   PROFILETYPE int
)
;
CREATE UNIQUE INDEX SQL160922151518770 ON "APPVISAMANAGER"."APP_USER"(IDUSER)
;
CREATE UNIQUE INDEX SQL160926171513260 ON "APPVISAMANAGER"."APP_USER"(LOGIN)
;
