CREATE TABLE "APPVISAMANAGER"."CHANGELOG"
(
   IDCHANGELOG int PRIMARY KEY NOT NULL,
   DESCRIPTION clob(255),
   OPERATIONTIME timestamp,
   USERCOMMENT clob(255),
   APPUSER int NOT NULL
)
;
ALTER TABLE "APPVISAMANAGER"."CHANGELOG"
ADD CONSTRAINT FKE4GRIFGUPGI6HU6BM3LYX8N8Q
FOREIGN KEY (APPUSER)
REFERENCES "APPVISAMANAGER"."APP_USER"(IDUSER)
;
CREATE UNIQUE INDEX SQL160922151519050 ON "APPVISAMANAGER"."CHANGELOG"(IDCHANGELOG)
;
CREATE INDEX SQL160922151519930 ON "APPVISAMANAGER"."CHANGELOG"(APPUSER)
;
