CREATE TABLE "APPVISAMANAGER"."MONASTERY"
(
   ID_MONASTERY int not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
   ADDR_AMPHER varchar(255),
   ADDR_COUNTRY varchar(255),
   ADDR_JANGWAT varchar(255),
   ADDR_NUMBER varchar(255),
   ADDR_ROAD varchar(255),
   ADDR_TAMBON varchar(255),
   MONASTERY_OF_JAOKANA varchar(255) NOT NULL,
   MONASTERY_NAME varchar(255),
   PHONE_NUMBER varchar(255)
)
;
CREATE INDEX SQL160926171150590 ON "APPVISAMANAGER"."MONASTERY"(MONASTERY_NAME)
;
CREATE UNIQUE INDEX SQL160922151519180 ON "APPVISAMANAGER"."MONASTERY"(ID_MONASTERY)
;
