CREATE TABLE "APPVISAMANAGER"."PASSPORT_SCAN"
(
   ID_PASSPORT_SCAN int not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
   CONTENT_ARRIVE_STAMP boolean NOT NULL,
   CONTENT_LAST_VISA_EXT boolean NOT NULL,
   CONTENT_VISA_SCAN boolean NOT NULL,
   PAGE_NUMBER int NOT NULL,
   MONASTIC_PROFILE int NOT NULL
)
;
ALTER TABLE "APPVISAMANAGER"."PASSPORT_SCAN"
ADD CONSTRAINT FKKQP267KLHGGYGMYFXHYCJLAL7
FOREIGN KEY (MONASTIC_PROFILE)
REFERENCES "APPVISAMANAGER"."MONASTIC_PROFILE"(ID_PROFILE)
;
CREATE INDEX SQL160922151520290 ON "APPVISAMANAGER"."PASSPORT_SCAN"(MONASTIC_PROFILE)
;
CREATE UNIQUE INDEX SQL160922151519330 ON "APPVISAMANAGER"."PASSPORT_SCAN"(ID_PASSPORT_SCAN)
;
CREATE UNIQUE INDEX SQL160926171948230 ON "APPVISAMANAGER"."PASSPORT_SCAN"
(
  MONASTIC_PROFILE,
  PAGE_NUMBER
)
;
