CREATE TABLE "APPVISAMANAGER"."TM30_NOTIFICATION_RESIDENCE"
(
   ID_FORM int not null primary key
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
   NOTIFICATION_DATE date NOT NULL
)
;
CREATE UNIQUE INDEX SQL161015152216961 ON "APPVISAMANAGER"."TM30_NOTIFICATION_RESIDENCE"(ID_FORM)
;
CREATE UNIQUE INDEX SQL161015152216960 ON "APPVISAMANAGER"."TM30_NOTIFICATION_RESIDENCE"(NOTIFICATION_DATE)
;